export const TABLE_WIDTH_M = 2.844;
export const TABLE_HEIGHT_M = 1.422;
export const BALL_DIAMETER_M = 0.0615;
export const BALL_RADIUS_M = BALL_DIAMETER_M / 2;
export const BALL_MASS_KG = 0.21;

export const CUSHION_THICKNESS_M = 0.05;
export const CUSHION_RESTITUTION = 0.72;
export const BALL_BALL_RESTITUTION = 0.95;
export const BALL_BALL_CONTACT_FRICTION = 0.05;

export const CUSHION_CONTACT_FRICTION_COEFFICIENT = 0.14;
export const CUSHION_CONTACT_REFERENCE_SPEED_MPS = 5.957692307692308;
export const CUSHION_CONTACT_TIME_EXPONENT = 1.2;
export const CUSHION_MAX_SPIN_MAGNITUDE = 0.615;
export const CUSHION_MAX_THROW_ANGLE_DEG = 55;
export const CUSHION_HEIGHT_M = 0.037;

export const SLIDING_FRICTION_COEFFICIENT = 0.2;
export const ROLLING_FRICTION_COEFFICIENT = 0.012;
export const GRAVITY_ACCELERATION_MPS2 = 9.81;
export const SLIP_SPEED_THRESHOLD_MPS = 0.01;

export const MAX_BALL_SPEED_MPS = 13.89;
export const STATIONARY_LINEAR_SPEED_THRESHOLD_MPS = 0.01;
export const STATIONARY_ANGULAR_SPEED_THRESHOLD_RADPS = 0.2;
export const PENETRATION_SLOP_M = 5e-5;
export const POSITION_CORRECTION_SCALE = 1.2;
