import type { StepRoomPhysicsConfig } from './room-physics-step.ts';
import { TABLE_GEOMETRY } from '../../shared-types/src/table-geometry.ts';

export const ROOM_SNAPSHOT_BROADCAST_INTERVAL_MS = 50;
export const ROOM_PHYSICS_SUBSTEPS = 12;
export const ROOM_PHYSICS_TABLE_WIDTH_M = TABLE_GEOMETRY.tableInnerWidthM;
export const ROOM_PHYSICS_TABLE_HEIGHT_M = TABLE_GEOMETRY.tableInnerHeightM;
export const ROOM_PHYSICS_BALL_RADIUS_M = TABLE_GEOMETRY.ballRadiusM;
export const ROOM_PHYSICS_COLLISION_PLANE_OFFSET_M = TABLE_GEOMETRY.effectiveCollisionPlaneOffsetM;
export const ROOM_PHYSICS_SHOT_END_LINEAR_SPEED_THRESHOLD_MPS = 0.01;
export const ROOM_PHYSICS_MAX_BALL_SPEED_MPS = 13.89;
export const ROOM_PHYSICS_BALL_BALL_RESTITUTION = 0.95;
export const ROOM_PHYSICS_BALL_MASS_KG = 0.21;
export const ROOM_PHYSICS_CUSHION_RESTITUTION = 0.72;
export const ROOM_PHYSICS_CUSHION_CONTACT_FRICTION = 0.14;
export const ROOM_PHYSICS_CUSHION_REFERENCE_SPEED_MPS = 5.957692307692308;
export const ROOM_PHYSICS_CUSHION_CONTACT_TIME_EXPONENT = 0.7;
export const ROOM_PHYSICS_CUSHION_MAX_SPIN_MAGNITUDE = 3.0;
export const ROOM_PHYSICS_CUSHION_MAX_THROW_ANGLE_DEG = 15;
export const ROOM_PHYSICS_RECOVERY_FALLBACK_ENABLED = true;
export const ROOM_PHYSICS_MAX_SUBSTEP_ENERGY_GAIN_J = 0.03;

export function createRoomPhysicsStepConfig(): StepRoomPhysicsConfig {
  return {
    dtSec: ROOM_SNAPSHOT_BROADCAST_INTERVAL_MS / 1000,
    substeps: ROOM_PHYSICS_SUBSTEPS,
    tableWidthM: ROOM_PHYSICS_TABLE_WIDTH_M,
    tableHeightM: ROOM_PHYSICS_TABLE_HEIGHT_M,
    ballRadiusM: ROOM_PHYSICS_BALL_RADIUS_M,
    shotEndLinearSpeedThresholdMps: ROOM_PHYSICS_SHOT_END_LINEAR_SPEED_THRESHOLD_MPS,
    maxBallSpeedMps: ROOM_PHYSICS_MAX_BALL_SPEED_MPS,
    ballBallRestitution: ROOM_PHYSICS_BALL_BALL_RESTITUTION,
    ballMassKg: ROOM_PHYSICS_BALL_MASS_KG,
    cushionRestitution: ROOM_PHYSICS_CUSHION_RESTITUTION,
    cushionContactFriction: ROOM_PHYSICS_CUSHION_CONTACT_FRICTION,
    cushionReferenceSpeedMps: ROOM_PHYSICS_CUSHION_REFERENCE_SPEED_MPS,
    cushionContactTimeExponent: ROOM_PHYSICS_CUSHION_CONTACT_TIME_EXPONENT,
    cushionMaxSpinMagnitude: ROOM_PHYSICS_CUSHION_MAX_SPIN_MAGNITUDE,
    cushionMaxThrowAngleDeg: ROOM_PHYSICS_CUSHION_MAX_THROW_ANGLE_DEG,
    recoveryFallbackEnabled: ROOM_PHYSICS_RECOVERY_FALLBACK_ENABLED,
    maxSubstepEnergyGainJ: ROOM_PHYSICS_MAX_SUBSTEP_ENERGY_GAIN_J,
  };
}
