services:
  bhc:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: bhc
    environment:
      PORT: "9900"
      STATIC_DIR: "/app/static"
    ports:
      - "9900:9900"
    restart: unless-stopped
